### ISSUE TITLE
Skyrim Immersive Creatures Special Edition

### ISSUE THREAD

**Issue by jonasschrottenbaum** [tiltedphoques/Mod-Compatibility#95]
# Mod information

Adds new creatures

#### Download link
https://www.nexusmods.com/skyrimspecialedition/mods/12680

#### Dependencies
- SkyUI

# Compatibility

> Mod is partially compatible. In general the creatures are synced but it happened several times during a few hours of playing that the other player saw a different creature. If it happens, this creature will have no animations. It just slides around without attacking the other player, so he can kill it without repercussions, but get the loot from the original.

> It also happened that a creature was invisible for one player, but so far this has only happened shortly after connecting to the server. Maybe there is an issue with the inital sync if the creature has already spawned in one players world prior to connecting
It could also be dependant on who enters an area first.

**Comment by Owlchemist** [comment]
Maybe this was fixed in 1.2? The problems described sound like random encounters desync that 1.2 addressed.

**Comment by bobbyroylee** [comment]
Does NOT work.  The syncing in 1.2 does NOT fix it.  Your teammates will sometimes not see the "Immersive creatures" OR it'll just be different creatures than you see.

**Comment by Willy-foxie** [comment]
We do see different creatures sometimes without a mod too. Some says, it's coop mod problem. I'd not say that Immersive Creatures raises this bug chance.

**Comment by KiraMikamy** [comment]
tried but definitevely wont sync proprely, too many creatures mismatch that broke a bit the immersion and we removed

**Comment by SegwayJesus** [comment]
Anyone else have the issue where it spawns increasingly more goblins during a raid? Im playing with 4 people and it got so bad we had to disable additional spawns.
[](url
![SkyrimTogether_qNh6SYvoiF](https://user-images.githubusercontent.com/17227725/183264290-30ca7062-f08b-48b1-a77a-eca049aeb01e.jpg)
)
